# Generated by Django 4.2.11 on 2025-08-03 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movie_backdrop_path_movie_country_movie_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMoodPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_preferences', models.JSONField(default=list, help_text='List of selected mood types')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mood_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Mood Preference',
                'verbose_name_plural': 'User Mood Preferences',
            },
        ),
        migrations.CreateModel(
            name='AnonymousMoodSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier for anonymous users', max_length=100, unique=True)),
                ('mood_preferences', models.JSONField(default=list, help_text='List of selected mood types')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anonymous Mood Session',
                'verbose_name_plural': 'Anonymous Mood Sessions',
                'indexes': [models.Index(fields=['session_id'], name='core_anonym_session_048463_idx'), models.Index(fields=['created_at'], name='core_anonym_created_fdefa1_idx')],
            },
        ),
    ]
