# Generated by Django 4.2.11 on 2025-08-03 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usermoodpreference_anonymousmoodsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousSavedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('tmdb_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.CharField(blank=True, max_length=32, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('genre_ids', models.JSONField(blank=True, default=list)),
                ('media_type', models.CharField(default='movie', max_length=20)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_liked', models.BooleanField(default=False)),
                ('is_watch_later', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Anonymous Saved Movie',
                'verbose_name_plural': 'Anonymous Saved Movies',
                'indexes': [models.Index(fields=['session_id', 'saved_at'], name='core_anonym_session_b672b7_idx'), models.Index(fields=['expires_at'], name='core_anonym_expires_430915_idx'), models.Index(fields=['tmdb_id'], name='core_anonym_tmdb_id_ad7714_idx')],
                'unique_together': {('session_id', 'tmdb_id', 'media_type')},
            },
        ),
        migrations.CreateModel(
            name='SavedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.CharField(blank=True, max_length=32, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('genre_ids', models.JSONField(blank=True, default=list)),
                ('media_type', models.CharField(default='movie', max_length=20)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('is_liked', models.BooleanField(default=False)),
                ('is_watch_later', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Movie',
                'verbose_name_plural': 'Saved Movies',
                'indexes': [models.Index(fields=['user', 'saved_at'], name='core_savedm_user_id_b8396d_idx'), models.Index(fields=['tmdb_id'], name='core_savedm_tmdb_id_664dbe_idx')],
                'unique_together': {('user', 'tmdb_id', 'media_type')},
            },
        ),
    ]
